apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodeoverlayips.iks.ibm.com
spec:
  group: iks.ibm.com
  names:
    kind: NodeOverlayIp
    listKind: NodeOverlayIpList
    plural: nodeoverlayips
    singular: nodeoverlayip
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          properties:
            gateway:
              description: Gateway the gateway IP address of the network (optional)
              type: string
            interface:
              description: Interface the interface to put the IP address on
              type: string
            interfaceLabel:
              description: InterfaceLabel the name of the overlay interface
              type: string
            ipAddr:
              description: IpAddr reserved in IPAM to configure on the node
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
