apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: staticroutes.iks.ibm.com
spec:
  group: iks.ibm.com
  names:
    kind: StaticRoute
    listKind: StaticRouteList
    plural: staticroutes
    singular: staticroute
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            gateway:
              description: Gateway the gateway the subnet is routed through (optional,
                discovered if not set)
              type: string
            subnet:
              type: string
          required:
          - subnet
          type: object
        status:
          properties:
            nodeStatus:
              items:
                properties:
                  device:
                    type: string
                  gateway:
                    type: string
                  hostname:
                    type: string
                required:
                - hostname
                - gateway
                - device
                type: object
              type: array
          required:
          - nodeStatus
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
