kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: overlay-ip-controller
subjects:
- kind: ServiceAccount
  name: overlay-ip-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: overlay-ip-controller
  apiGroup: rbac.authorization.k8s.io
